// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucnthhdpilmpfssrodtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbnRoaGRwaWxtcGZzc3JvZHR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMDM5NjEsImV4cCI6MjA1NTU3OTk2MX0.EUiam0BQOdkQOQFQkxCBPkQGoYPLA_BKI4SY-jP2Iyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);